### ISSUE TITLE
Track votes by user; allow poll to be configured to allow only logged-in voters

### ISSUE THREAD

**Issue by mudlock** [electology/approval_frame#16] opened 2014-06-30 01:36 UTC

**Comment by rupalkhilari** [comment] 2015-07-26 08:17
I would like to look into this issue. I believe it would add another option to configure a newly created poll. (Looks like we might be moving towards creating an additional 'Poll Settings' section in the 'Create Poll' page - which would contain the poll 'edit' options). 
Perhaps we could also integrate an optional [social authentication](https://python-social-auth.readthedocs.org/en/latest/) requirement to vote. Please let me know in case there are any other better, more preferred approaches to this.  
Thanks!

**Comment by ashimaathri** [comment] 2015-07-27 12:29
@rupalkhilari thanks for volunteering to look into this issue. I believe this issue is a duplicate of #15 and #7. @Brianjr0428 is already looking into #15 and has added a 'Manage Polls' section with each poll having edit/delete/suspend options. It would be great if you could look into #7 as that is the only blocking issue left before this app becomes usable.
Social authentication would also be a useful feature to have but we should open a new issue for it with medium priority.

**Comment by rupalkhilari** [comment] 2015-07-28 17:11
Yes, this one is similar to #7 . I'm not sure if #7 should also look into perhaps integrating an option for something like an [evercookie](https://github.com/gdmka/django-evercookie) - haven't tried that earlier though. 
I shall look into adding the vote tracking based on the user/email. We could have this as a configurable option for the poll at first and maybe switch it to the default behavior if it seems fine.

**Comment by ashimaathri** [comment] 2015-07-29 01:04
Thanks @rupalkhilari! That'll be great. I did not understand the configurable part though. Could you elaborate a little bit on that?

I just read up on evercookie and I'm wondering if we really need them. It looks like their main use case is to track user activity and hence know their preferences. Our main use case is to collect votes *without* recording who voted for what. So, I think we should simply use normal http cookies.
But thanks for pointing me to this resource! Now I have to go through all the possible places that websites can store their 'zombie' cookies in and purge them on my machine :smile_cat:

**Comment by rupalkhilari** [comment] 2015-07-29 18:20
Hehe :smile: , yes I believe it I suggested it only to overcome the fact that regular cookies are not cross browser :( . But I went through other polling applications like SurveyMonkey and BallotBin and they too seem to be using regular cookies. 
By configurable, I was suggesting that the poll creator could be given a choice of the following while creating the poll:
* Whether they want the poll to be restricted to only those with logins/email. (as in this ticket)
* Whether they want the poll to function as it does now (without any restriction as such)
* Whether they would want the application to use cookies to store user data without requiring logins/email.
* Whether they would want the application to use IP addresses to identify unique voters (though I know this fails for larger networks behind a proxy or dynamic IPs)

I understand each of the following has its own drawbacks though. :disappointed: 
Maybe after poll creation, we could redirect them to the 'edit polls' page that would come out of #66 where they could configure their settings. 
Do let me know what you think. Thanks!

**Comment by rupalkhilari** [comment] 2015-08-03 20:26
Hi @ashimaathri , I realized that I might be a little busy until the end of this month, so if anyone else is interested in looking into this by then, please do. Thanks!

**Comment by ashimaathri** [comment] 2015-08-04 00:17
@rupalkhilari I like the idea of making the poll configurable with regards to voting. I don't think the last two options are required right now. Lets get the simplest version working and then we can go forward with the other configurations.

**Comment by rupalkhilari** [comment] 2015-10-17 17:23
Added a 'Poll Settings' panel in the 'create poll' page - through which the poll administrator can control who can vote in the poll.

It now allows two types of polls:
1) Anyone can vote, any number of times (previous behavior)
2) Only registered voters can vote, once - requires login.

This does not include the ability to update ones existing ballot. We could perhaps handle that in another ticket.

**Comment by rupalkhilari** [comment] 2015-10-17 17:30
https://github.com/electology/approval_frame/issues/75 has been raised to allow a registered user to update an existing ballot.

**Comment by rupalkhilari** [comment] 2015-10-17 17:31
Closed by https://github.com/electology/approval_frame/pull/74

**Closed by rupalkhilari** 2015-10-17 17:31 UTC
Labels: enhancement, priority:high
